#!/usr/bin/env bash
# Render Formula/ttmux.rb for a released version and push it to the tap.
#
# The formula installs the binaries that the release workflow already built,
# so this reads their checksums from the release rather than computing any.
#
# usage: scripts/update-tap.sh v0.1.0
set -euo pipefail

TAG="${1:?usage: update-tap.sh <tag>}"
VERSION="${TAG#v}"
REPO="${REPO:-statico/ttmux}"
TAP="${TAP:-statico/homebrew-tap}"

TARGETS=(
  aarch64-apple-darwin
  x86_64-apple-darwin
  aarch64-unknown-linux-gnu
  x86_64-unknown-linux-gnu
)

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

for t in "${TARGETS[@]}"; do
  gh release download "$TAG" --repo "$REPO" \
    --pattern "ttmux-$t.tar.gz.sha256" --dir "$work" --clobber
done

# The .sha256 files hold "<hash>  <filename>", so the hash is the first field.
# A function rather than an associative array, because macOS ships bash 3.2.
sha() { awk '{print $1}' "$work/ttmux-$1.tar.gz.sha256"; }
url() { echo "https://github.com/$REPO/releases/download/$TAG/ttmux-$1.tar.gz"; }

# The token goes in the URL so this works from CI, where there is no
# credential helper and no ssh key.
if [ -n "${GH_TOKEN:-}" ]; then
  clone="https://x-access-token:$GH_TOKEN@github.com/$TAP.git"
else
  clone="https://github.com/$TAP.git"
fi
git clone --depth 1 "$clone" "$work/tap"
cat > "$work/tap/Formula/ttmux.rb" <<EOF
# Generated by scripts/update-tap.sh in $REPO. Edits here are overwritten
# by the next release.
class Ttmux < Formula
  desc "Modern multiplexer alternative with tiling and free-floating panes"
  homepage "https://github.com/$REPO"
  version "$VERSION"
  license "MIT"

  on_macos do
    on_arm do
      url "$(url aarch64-apple-darwin)"
      sha256 "$(sha aarch64-apple-darwin)"
    end
    on_intel do
      url "$(url x86_64-apple-darwin)"
      sha256 "$(sha x86_64-apple-darwin)"
    end
  end

  on_linux do
    on_arm do
      url "$(url aarch64-unknown-linux-gnu)"
      sha256 "$(sha aarch64-unknown-linux-gnu)"
    end
    on_intel do
      url "$(url x86_64-unknown-linux-gnu)"
      sha256 "$(sha x86_64-unknown-linux-gnu)"
    end
  end

  def install
    bin.install "ttmux"
  end

  test do
    assert_match "ttmux #{version}", shell_output("#{bin}/ttmux -V")
    # --where needs no terminal, so it works in the sandbox.
    assert_match "ttmux.toml", shell_output("#{bin}/ttmux --where")
  end
end
EOF

cd "$work/tap"
# Staged first: a formula that does not exist yet is untracked, and an
# untracked file never shows up in `git diff`.
git add Formula/ttmux.rb
if git diff --cached --quiet; then
  echo "tap already at $VERSION"
  exit 0
fi
git -c user.name="Claude Code" -c user.email="claude@anthropic.com" \
  commit -q -m "ttmux $VERSION"
git push -q "$clone" HEAD:main
echo "tap updated to $VERSION"
