//! ttmux — a modern terminal multiplexer.
pub mod action;
pub mod agent;
pub mod app;
pub mod client;
pub mod color_picker;
pub mod config;
pub mod graphics;
pub mod input;
pub mod layout;
pub mod line_edit;
pub mod onboarding;
pub mod proto;
pub mod pty;
pub mod render;
pub mod server;
pub mod settings_ui;
pub mod status;
pub mod widget;
